Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  # Set VM name in VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-vagrant"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  # Network settings (optional)
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Shared folder (optional)
  config.vm.synced_folder ".", "/vagrant"
end
